[colors.primary]
background = "#161616"
foreground = "#ffffff"

[colors.search.matches]
foreground = CellBackground
background = '#ee5396'

[colors.normal]
black = '#262626'
magenta = '#ff7eb6'
green = '#42be65'
yellow = "#ffe97b"
blue = '#33b1ff'
red = '#ee5396'
cyan = '#3ddbd9'
white = '#dde1e6'

[colors.bright]
black = '#393939'
magenta = '#ff7eb6'
green = '#42be65'
yellow = "#ffe97b"
blue = '#33b1ff'
red = '#ee5396'
cyan = '#3ddbd9'
white = '#ffffff'

[font]
size = 12

[font.bold]
family = "Inconsolata Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Inconsolata Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Inconsolata Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Inconsolata Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[window]
decorations = "none"
opacity = 0.9
