name: Build, rechunk, and push image
on:
  schedule:
    - cron: 45 21 */2 * * # every other day, at 21:45 UTC
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Log in to quay
        uses: redhat-actions/podman-login@v1
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - uses: actions/checkout@v5
        with:
          lfs: "true"

      - id: makefile
        shell: bash
        run: |
          make tmp/Containerfile
          echo "version=$(make print-version)" >> $GITHUB_OUTPUT

      - uses: jharmison-redhat/action-bootc-build@main
        with:
          file: tmp/Containerfile
          labels: |
            dev.jharmison.git-repository=${{ github.server_url }}/${{ github.repository }}
            dev.jharmison.commit=${{ github.sha }}
            org.opencontainers.image.version=${{ steps.makefile.outputs.version }}
          extra-args: --retry=6 --retry-delay=10s
          push: "true"
          tag: quay.io/solacelost/bootc-image:latest
